### ISSUE TITLE
Using Ganeti with xen/opennebula is it possible?

### ISSUE THREAD

**Issue by topstarnetwork** [sigmike/ganeti#1]
Hello,
I would like to Use Ganeti with xen/opennebula,
is this possible or Ganeti does what Opennebula does????

As I found a project that uses openstack instead here 
https://www.synnefo.org/about/

and as I find Opennebula vith more features then Openstack,
Is it possible to use Opennebula instead of openstack?

Regards, Heather

**Comment by sigmike** [comment]
Hello,
Sorry this is not the official ganeti repository. You should ask your question here: http://groups.google.com/group/ganeti
